import type { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  filterBar: { display: "flex", gap: "0.75rem", flexWrap: "wrap", alignItems: "flex-end", background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, padding: "0.85rem 1.1rem", marginBottom: "1.25rem" },
  chip: { border: "1px solid var(--border)", borderRadius: 99, padding: "0.4rem 0.85rem", fontSize: "0.82rem", fontWeight: 600, cursor: "pointer", transition: "all .15s", fontFamily: "var(--font-body)" },
  dateInput: { background: "var(--surface2)", border: "1px solid var(--border)", borderRadius: 8, padding: "0.45rem 0.65rem", color: "var(--text)", fontSize: "0.85rem", outline: "none" },
  miniLabel: { fontSize: "0.7rem", fontWeight: 600, color: "var(--muted)", textTransform: "uppercase" as const, letterSpacing: "0.05em" },
  btnPrimary: { background: "var(--accent)", color: "#eff5ff", border: "none", borderRadius: 8, padding: "0.55rem 1.1rem", fontFamily: "var(--font-head)", fontSize: "0.85rem", fontWeight: 700, cursor: "pointer" },
  btnSecondary: { background: "transparent", color: "var(--accent)", border: "1px solid var(--accent)", borderRadius: 8, padding: "0.55rem 1.1rem", fontFamily: "var(--font-head)", fontSize: "0.85rem", fontWeight: 700, cursor: "pointer" },
  errorBox: { background: "rgba(248,81,73,.12)", border: "1px solid rgba(248,81,73,.3)", borderRadius: 8, padding: "0.75rem 1rem", color: "var(--red)", fontSize: "0.88rem", marginBottom: "1rem" },
  emptyState: { display: "flex", flexDirection: "column" as const, alignItems: "center", padding: "4rem 2rem", background: "var(--surface)", border: "1px dashed var(--border)", borderRadius: 14 },
  emptyIconWrap: { width: 72, height: 72, borderRadius: 16, background: "var(--surface2)", border: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "center" },
  skeleton: { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, opacity: 0.5 },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: "1rem" },
  kpiGroupLabel: { fontSize: "0.75rem", fontWeight: 700, color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.04em", marginBottom: "0.5rem" } as CSSProperties,
  statCard: { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, padding: "1.1rem 1.25rem" },
  statCardTop: { display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.5rem" },
  statIconWrap: { width: 28, height: 28, borderRadius: 6, background: "var(--surface2)", border: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  statLabel: { fontSize: "0.72rem", fontWeight: 600, color: "var(--muted)", textTransform: "uppercase" as const, letterSpacing: "0.05em" },
  statValue: { fontFamily: "var(--font-head)", fontSize: "1.55rem", fontWeight: 700, color: "var(--accent)", lineHeight: 1.1 },
  statSub: { fontSize: "0.72rem", color: "var(--muted)" },
  card: { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, padding: "1.1rem 1.25rem" },
  cardTitle: { fontFamily: "var(--font-head)", fontSize: "0.82rem", fontWeight: 700, color: "var(--muted)", textTransform: "uppercase" as const, letterSpacing: "0.06em", marginBottom: "0.9rem" },
  heroCard: { background: "linear-gradient(145deg, rgba(45,106,79,.35) 0%, rgba(45,106,79,.1) 100%)", border: "1px solid rgba(45,106,79,.4)", borderRadius: 12, padding: "1.25rem", display: "flex", flexDirection: "column" as const, gap: "0" },
  heroBadge: { display: "inline-flex", alignItems: "center", gap: "0.35rem", background: "rgba(232,160,69,.2)", border: "1px solid rgba(232,160,69,.4)", color: "var(--accent)", fontSize: "0.7rem", fontWeight: 700, padding: "0.2rem 0.65rem", borderRadius: 99, marginBottom: "0.6rem", letterSpacing: "0.05em", textTransform: "uppercase" as const, alignSelf: "flex-start" },
  heroName: { fontFamily: "var(--font-head)", fontSize: "1.1rem", fontWeight: 700, color: "var(--text)", marginBottom: "0.3rem", lineHeight: 1.25 },
  heroCode: { background: "rgba(0,0,0,.25)", padding: "0.1rem 0.4rem", borderRadius: 4, fontFamily: "monospace", fontSize: "0.75rem" },
  heroStat: { display: "flex", flexDirection: "column" as const, background: "rgba(0,0,0,.2)", borderRadius: 8, padding: "0.5rem 0.75rem", flex: "1 1 70px", marginTop: "0.75rem" },
  heroStatVal: { fontFamily: "var(--font-head)", fontSize: "1rem", fontWeight: 700, color: "var(--accent)", lineHeight: 1.1, fontVariantNumeric: "tabular-nums" as const },
  heroStatSub: { fontSize: "0.68rem", color: "rgba(255,255,255,.45)", marginTop: "0.15rem" },
  nBox: { display: "flex", flexDirection: "column" as const, alignItems: "center", justifyContent: "center", background: "rgba(45,106,79,.08)", border: "1px solid rgba(45,106,79,.2)", borderRadius: 12, padding: "1.5rem 2rem", gap: "0.35rem" },
  nVal: { fontFamily: "var(--font-head)", fontSize: "2.5rem", fontWeight: 800, color: "var(--accent)", lineHeight: 1 },
  nLabel: { fontSize: "0.78rem", color: "var(--muted)", textAlign: "center" as const },
  table: { width: "100%", borderCollapse: "collapse" as const },
  th: { fontSize: "0.68rem", fontWeight: 600, color: "var(--muted)", textTransform: "uppercase" as const, letterSpacing: "0.05em", padding: "0.4rem 0.5rem", textAlign: "left" as const, borderBottom: "1px solid var(--border)", background: "var(--surface2)", whiteSpace: "nowrap" as const },
  td: { padding: "0.5rem 0.5rem", fontSize: "0.82rem", color: "var(--text)", verticalAlign: "middle" as const },
};
